### ISSUE TITLE
Reformat config file

### ISSUE THREAD

**Issue by MaaniBeigy** [AASAAM/palantir#4]
In roadmap to release version 1.0.0, It is required to have a config file like:
```toml
[backends]

  [[backends.webapp1]]
  target = "http://127.0.0.1:9000"
  health = "/health"

  [[backends.webapp2]]
  target = "http://127.0.0.1:9000"
  health = "/health"

  [[backends.webapp3]]
  target = "https://127.0.0.1:9000"
  health = "/health"
  ssl_ca = "/path/to/ca.pem"

[[frontends]]

  [frontends.sample]

    [[frontends.sample.backends]]
    target = "webapp1"
    weight = 5.0

    [[frontends.sample.backends]]
    target = "webapp2"
    weight = 2.0

    [[frontends.sample.backends]]
    target = "webapp3"
    backup = true
```
